name: grandpa
version: "0.0.0.0"

dependencies:
  - base

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -fwarn-tabs
    - -O0

tests:
  tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - grandpa
      - hspec
      - hspec-discover
